// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vfcarecnhgszrxgpexhl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZmY2FyZWNuaGdzenJ4Z3BleGhsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjIyOTEzNDgsImV4cCI6MjA3Nzg2NzM0OH0.gm2RJ4YGjQ7smKJeOKo2A8xpXBelzsTbslqFeV_6vv0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});